### PR TITLE
Rename media to atomic

### PR DESCRIPTION
**Pull request by sugarshin**
refs: https://github.com/facebook/draft-js/commit/0096d9873e5f7e98145c0a835a52a42f54003306

### CODE REVIEW

**Comment by sstur** [comment]
I'm good with the first commit, 1f0aee6, but why are we adding the compiled code to the repo?

**Comment by sugarshin** [comment]
Sorry miss... need dependecy from my production. is fixed

**Comment by jaaberg** [comment]
Now it's good :+1:

**Comment by sstur** [comment]
Thanks for the contribution. This looks good to me.

**Pull request merged**
