### PR TITLE
fix import `immutable`

### PR DESCRIPTION
**Pull request by sugarshin**
fix `import` style

### CODE REVIEW

**Comment by sstur** [comment]
Looks good to me. But the tests are failing (Flow). I'll see if I can help you figure out why..

**Comment by sugarshin** [comment]
I think problem of node version. try version node v5 is test fail. on my local machine

```
$ node -v
v5.10.1
```

try changing travis.

**Comment by sugarshin** [comment]
Version that I've tried in the local is v4.

**Comment by sstur** [comment]
This is now in #17. I've added you to the contributors list also. Thanks!

**Pull request closed without merging**
