### PR TITLE
Feature/get selected blocks

### PR DESCRIPTION
**Pull request by johanneslumpe**
This has no flow types yet, as I haven't worked with flow before. Will add those soon. If somebody wants to enlighten me regarding that, that'd be cool.

### CODE REVIEW

**Comment by sstur** [comment]
Thanks @johanneslumpe. I will get some instructions in the readme about Flow types. (Flow is probably the largest barrier to contributions, but hopefully we can make that easier). However, I would like to see tests as part of any feature addition (ideally, any PR).

The convention in this repo (copied from FB) is to put the test for a file `src/foo.js` in `src/__tests__/foo-test.js` so the test file is somewhat close to the source file in the directory structure (one subfolder away).

Besides taht this code looks good.

**Comment by johanneslumpe** [comment]
@sstur Will add those shortly :)

**Comment by johanneslumpe** [comment]
@sstur and there are the first tests! I think we should have some CI integration here which auto-runs the tests, what do you think?

**Comment by sstur** [comment]
This looks good to me. Feel free to merge when you're ready.

I agree about the continuous integration. I'll setup travis-ci.
Edit: done. travis-ci is added in #10

Thanks!

**Pull request merged**
