### PR TITLE
Feature/call modifier for selected blocks

### PR DESCRIPTION
**Pull request by johanneslumpe**
Depends on and thus contains https://github.com/draft-js-utils/draft-js-utils/pull/5

### CODE REVIEW

**Comment by sstur** [comment]
This code looks good. Hit me with some tests and we'll get it merged.

**Comment by johanneslumpe** [comment]
@sstur Will add those shortly :)

**Comment by johanneslumpe** [comment]
@sstur And here are the tests. I will try to add flow types to the merged stuff soon.

**Comment by sstur** [comment]
Thanks @johanneslumpe. This looks good to me! Feel free to merge at your convenience.

**Pull request merged**
